#!/usr/bin/env sh

# install all the programs in programs.csv

set -x # echo commands
set -e # exit on failure

# ignore the first line (headers)
# https://stackoverflow.com/questions/339483/how-can-i-remove-the-first-line-of-a-text-file-using-bash-sed-script
tail -n +2 ubuntu_programs.csv  > /tmp/programs.csv

while IFS="," read -r program comment; do
    sudo apt-get install $program -y
done < /tmp/programs.csv

# install spaceship prompt for zsh.
# normally I would write this in the loop like the other programs
# but it has unsafe perms and I don't quite know how unsafe that is.
# so I think it makes sense to keep this in its own area
sudo npm install -g spaceship-prompt --unsafe-perm=true

# install the brave browser
sudo apt install apt-transport-https curl
curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
sudo apt update
sudo apt install brave-browser

# install fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/workspace/fzf
~/workspace/fzf/install
