#!/usr/bin/env sh

# install all the programs in programs.csv

# ignore the first line (headers)
# https://stackoverflow.com/questions/339483/how-can-i-remove-the-first-line-of-a-text-file-using-bash-sed-script
tail -n +2 programs.csv  > /tmp/programs.csv

while IFS="," read -r program comment; do
    sudo apt-get install $program -y
done < /tmp/programs.csv
